# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('1', 'Solteiro'), ('2', 'Casado'), ('3', 'Viúvo'), ('4', 'Divorciado'), ('5', 'Separado')], max_length=1)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
